eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost

microservice:
  payment-service:
    endpoints:
      endpoint:
        uri: http://PAYMENT-SERVICE/payment/doPayment
  order-service:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE/order/bookOrder
datasource:
    url: jdbc:mysql://localhost:3306/jrtpprojo
    username: KANHA
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  
    show-sql: true
